name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Test
      run: dotnet test ./PractiseFunction.Test/
    - name: Restore dependencies
      run: dotnet restore ./src/PractiseFunction
    - name: Build
      run: dotnet build --no-restore /p:ContinuousIntegrationBuild=true ./src/PractiseFunction
    - name: Test
      run: dotnet test --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=opencover ./src/PractiseFunction
    - name: Codecov
      uses: codecov/codecov-action@v1
